version: 1.0.{build}

environment:
  NODE_ENV: 'development'

install:
  - ps: Install-Product node 20
  - cd client && npm cache clean --force
  - cd client && npm install

build_script:
  - mkdir C:\Users\appveyor\AppData\Roaming\npm
  - cd client && npm ls webpack-cli
  - cd client && npm run build

deploy_script:
  - ps: |
      git config --global user.email "evgenia.maksimovna00@gmail.com"
      git config --global user.name "Евгения"
      cd client
      npx gh-pages -d dist -r https://%GITHUB_TOKEN%@github.com/FilSado/chat-project.git

artifacts:
  - path: client/dist
    name: client-dist