version: 1.0.{build}

environment:
  NODE_ENV: 'production'

install:
  - ps: Install-Product node 18
  - cd client && npm install

build_script:
  - cd client && npm install
  - cd client && npm run build





artifacts:
  - path: client/dist
    name: client-dist

deploy:
  - provider: GitHubPages
    auth_token:
      secure: <GITHUB_TOKEN> 
    branch: gh-pages
    folder: client/dist
    on:
      branch: main
