version: 1.0.{build}

environment:
  NODE_ENV: 'production'

install:
  - ps: Install-Product node 20
  - ps: Remove-Item -Recurse -Force client\node_modules, client\package-lock.json
  - cd client && npm cache clean --force
  - cd client && npm install

build_script:
- cd client && npm ls webpack-cli
- cd client && npm run build

artifacts:
  - path: client/dist
    name: client-dist

deploy:
  - provider: GitHubPages
    auth_token:
      secure: <GITHUB_TOKEN>
    branch: gh-pages
    folder: client/dist
    on:
      branch: main

