version: 1.0.{build}

environment:
  NODE_ENV: 'production'

install:
  - ps: Install-Product node 20
  - ps: if (Test-Path client\node_modules) { Remove-Item client\node_modules -Recurse -Force }
  - ps: if (Test-Path client\package-lock.json) { Remove-Item client\package-lock.json -Force }
  - cd client && npm cache clean --force
  - cd client && npm install

build_script:
  - mkdir C:\Users\appveyor\AppData\Roaming\npm
  - cd client && npm ls webpack-cli
  - cd client && npm run build

artifacts:
  - path: client/dist
    name: client-dist

deploy:
  - provider: GitHubPages
    auth_token:
      secure: <GITHUB_TOKEN>
    branch: gh-pages
    folder: client/dist
    on:
      branch: main


